In [1]:
import numpy as np

In [2]:
#tao mang
a = np.array([2,3,4])

#in mang
print(a)

#in ra mot phan tu
element = a[1]
print(element)

[2 3 4]
3


In [6]:
#tao mang 2 chieu
matrix = np.array([[1,2,3],[7,8,9],[6,5,4]])
print('Matrix: ')
print(matrix)

#in mot phan tu
element = matrix[1, 2]
print(element)

Matrix: 
[[1 2 3]
 [7 8 9]
 [6 5 4]]
9


In [8]:
#Cach tao mang
#tao mang toan la so 0
a = np.zeros(3)
print(a)

# Tao mang toan so 1
a = np.ones(3)
print(a)

# Tao mang
a = np.empty(3)
print(a)

# Tao mang tu 0 den 50
a = np.arange(50)
print(a)

# Tao mang gom cac phan tu voi khoang cach deu nhau
a = np.linspace(0, 7, num=5)
print(a)


# Xac dinh kieu du lieu
a = np.ones(5, dtype=np.int64)
a

[0. 0. 0.]
[1. 1. 1.]
[1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[0.   1.75 3.5  5.25 7.  ]


array([1, 1, 1, 1, 1], dtype=int64)

In [12]:
# Them, xoa, sap xep mang
# Tao mang
arr = np.array([3, 7, 1, 9, 5])
print(arr)

# Sap xep
arr = np.sort(arr)
print(arr)

# Sap xep nguoc
arr = np.sort(arr)[::-1]
print(arr)

#Them phan tu vao mang
arr = np.append(arr, 11)
print(arr)

# Xoa di mot vi tri nao do trong mang
arr = np.delete(arr, 1)
print(arr)

[3 7 1 9 5]
[1 3 5 7 9]
[9 7 5 3 1]
[ 9  7  5  3  1 11]
[ 9  5  3  1 11]


In [13]:
# Tao mot mang 2 chieu
arr = np.array([[3, 1, 2],
                [4, 5, 9],
                [8, 6, 5]])

sap_xep_theo_hang = np.sort(arr, axis=1) #tang dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = np.sort(arr, axis=0) #tang dan
print(sap_xep_theo_cot)

[[1 2 3]
 [4 5 9]
 [5 6 8]]
[[3 1 2]
 [4 5 5]
 [8 6 9]]


In [14]:
# Tao mot mang 2 chieu
arr = np.array([[3, 1, 2],
                [4, 5, 9],
                [8, 6, 5]])

sap_xep_theo_hang = -np.sort(-arr, axis=1) #giam dan
print(sap_xep_theo_hang)

sap_xep_theo_cot = -np.sort(-arr, axis=0) #giam dan
print(sap_xep_theo_cot)

[[3 2 1]
 [9 5 4]
 [8 6 5]]
[[8 6 9]
 [4 5 5]
 [3 1 2]]


In [15]:
# Tạo một mảng 2 chieu
arr = np.array([[1, 2, 3], [4, 5, 6],[9,8,7]])

#Sd cac thuoc tinh de lay thong tin ve mang
so_chieu = arr.ndim  #So chieu
kich_thuoc = arr.size  #Kich thuoc
hinh_dang = arr.shape  #Hinh dang(so hang x so cot)

print("Số chiều:", so_chieu)
print("Kích thước:", kich_thuoc)
print("Hình dạng:", hinh_dang)

Số chiều: 2
Kích thước: 9
Hình dạng: (3, 3)


In [16]:
# Chuyen doikieu du lieu
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5.]


In [18]:
#Thay doi hinh dang cua mang
arr = np.array([1, 2, 3, 7, 8, 9])
reshaped_arr = arr.reshape(2,3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3,2)
print(reshaped_arr)

[[1 2 3]
 [7 8 9]]
[[1 2]
 [3 7]
 [8 9]]


In [19]:
#chuyen thanh mang 1 chieu
reshaped_arr = reshaped_arr.flatten()
print(reshaped_arr)

[1 2 3 7 8 9]


In [20]:
# Cat lat mang
arr = np.array([1, 2, 3, 4, 5])

sub_arr = arr[1:4]  #Cat tu phan tu 1 den 4
print(sub_arr) # 2 3 4 5

sub_arr = arr[:-1]
print(sub_arr)

sub_arr = arr[-2:]
print(sub_arr)

[2 3 4]
[1 2 3 4]
[4 5]


In [21]:
#Chuyen vi mang
arr = np.array([[1, 2, 3], [4, 6, 9]])
print(arr)
#De chuyen vi mang ta sd .T hoac ham numpy.transpose()
transposed_arr = arr.T
print(transposed_arr)

[[1 2 3]
 [4 6 9]]
[[1 4]
 [2 6]
 [3 9]]


In [22]:
# Noi mang
arr1 = np.array([1, 2, 3])
arr2 = np.array([9,7,5])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 9 7 5]


In [23]:
# HAM TINH TONG (SUM)
# HAM numpy.sum() chho phep tinh tong cac phan tu trong mang
arr = np.array([2,4,6,8,10])
total = np.sum(arr)
print("Tong: ", total)

# HAM TINH TRUNG BINH (MEAN)
# Ham numpy.mean() tinh gia tri trung binh cua cac phan tu trong mang
average = np.mean(arr)
print("Gia tri trung binh: ", average)

# HAM TIM GIA TRI LON NHAT VA NHO NHAT(MIN & MAX)
# Ham numpy.max() & numpy.min() dung de tim gia tri lon nhat va nho nhat trong mang
max_value = np.max(arr)
min_value = np.min(arr)
print("Gia tri lon nhat: ", max_value)
print("Gia tri nho nhat: ", min_value)

# HAM TINH DO LECH CHUAN (STANDARD DEVIATION)
# Ham numpy.var() tinh do lech chuan cua mang, do luong muc do phan tan cua du lieu
std_deviation = np.std(arr)
print("Do lech chuan cua mang: ", std_deviation)

# HAM TINH PHUONG SAI(VARIANCE)
# Ham numpy.var() tinh phuong sai cua mang, do luong muc do bien thien cua du lieu
variance = np.var(arr)
print("Phuong sai cua mang: ", variance)

# HAM TINH TONG TICH CHAP (DOT PRODUCT)
# Ham numpy.dot() tinh tong tich chap cua 2 mang (VECTOR)
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print("Tong tich chap cua arr1 va arr2: ", dot_product)

Tong:  30
Gia tri trung binh:  6.0
Gia tri lon nhat:  10
Gia tri nho nhat:  2
Do lech chuan cua mang:  2.8284271247461903
Phuong sai cua mang:  8.0
Tong tich chap cua arr1 va arr2:  32
